//! Model struct for the Card type

use serde::{Serialize, Deserialize};

use super::Address;

/// This is a model struct for Card type.
#[derive(Clone, Debug, Default, Deserialize, Hash, PartialEq, Serialize)]
pub struct Card {
    /// Unique ID for this card. Generated by Square.
    pub id: Option<String>,
    /// Indicates a card's brand, such as `VISA` or `MASTERCARD`.
    pub card_brand: Option<String>,
    /// The last 4 digits of the card number.
    pub last_4: Option<String>,
    /// The expiration month of the associated card as an integer between 1 and 12.
    pub exp_month: Option<i32>,
    /// The four-digit year of the card's expiration date.
    pub exp_year: Option<i32>,
    /// The name of the cardholder.
    pub cardholder_name: Option<String>,
    /// Represents a postal address in a country. For more information, see [Working with
    /// Addresses](https://developer.squareup.com/docs/build-basics/working-with-addresses).
    pub billing_address: Option<Address>,
    /// Intended as a Square-assigned identifier, based on the card number, to identify the card
    /// across multiple locations within a single application.
    pub fingerprint: Option<String>,
    /// **Required** The ID of a customer created using the Customers API to be associated with the
    /// card.
    pub customer_id: Option<String>,
    /// The ID of the merchant associated with the card.
    pub merchant_id: Option<String>,
    /// An optional user-defined reference ID that associates this card with another entity in an
    /// external system. For example, a customer ID from an external customer management system.
    pub reference_id: Option<String>,
    /// Indicates whether or not a card can be used for payments.
    pub enabled: Option<bool>,
    /// Indicates a card's type, such as `CREDIT` or `DEBIT`.
    pub card_type: Option<String>,
    /// Indicates a card's prepaid type, such as `NOT_PREPAID` or `PREPAID`.
    pub prepaid_type: Option<String>,
    /// The first six digits of the card number, known as the Bank Identification Number (BIN). Only
    /// the Payments API returns this field.
    pub bin: Option<String>,
    /// Current version number of the card. Increments with each card update. Requests to update an
    /// existing Card object will be rejected unless the version in the request matches the current
    /// version for the Card.
    pub version: Option<i32>,
}
