//! Model struct for DisableCardResponse type

use serde::Deserialize;

use super::{errors::Error, Card};

/// This is a model struct for DisableCardResponse type
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq)]
pub struct DisableCardResponse {
    /// Information on errors encountered during the request.
    pub errors: Option<Vec<Error>>,
    /// Represents the payment details of a card to be used for payments. These details are
    /// determined by the payment token generated by Web Payments SDK.
    pub card: Card,
}
