//! Model struct for TenderCardDetails type

use serde::Deserialize;

use super::Card;

/// This is a model struct for TenderCardDetails type.
#[derive(Clone, Debug, Default, Deserialize, Hash, PartialEq)]
pub struct TenderCardDetails {
    /// Indicates the card transaction's current status.
    pub status: String,
    /// Represents the payment details of a card to be used for payments. These details are
    /// determined by the payment token generated by Web Payments SDK.
    pub card: Card,
    /// Indicates the method used to enter the card's details.
    pub entry_method: String,
}
