//! Model struct for TenderCardDetails type

use serde::{Deserialize, Serialize};

use super::{
    enums::{TenderCardDetailsEntryMethod, TenderCardDetailsStatus},
    Card,
};

/// This is a model struct for TenderCardDetails type.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct TenderCardDetails {
    /// Indicates the card transaction's current status.
    pub status: TenderCardDetailsStatus,
    /// Represents the payment details of a card to be used for payments. These details are
    /// determined by the payment token generated by Web Payments SDK.
    pub card: Card,
    /// Indicates the method used to enter the card's details.
    pub entry_method: TenderCardDetailsEntryMethod,
}
